from __future__ import absolute_import, print_function, unicode_literals


PC12_NUMBER_OF_TRACKS = 12

PC12_MIDI_CHANNEL_INDEX_PERFORMANCE_PAGE = 0
PC12_MIDI_CHANNEL_INDEX_EQ_PAGE = 1
PC12_MIDI_CHANNEL_INDEX_COMPRESSION_PAGE = 2

PC12_POT_ROW_A_CC_BASE = 1
PC12_POT_ROW_B_CC_BASE = 13
PC12_POT_ROW_C_CC_BASE = 25
PC12_POT_ROW_D_CC_BASE = 37
PC12_POT_ROW_E_CC_BASE = 49
PC12_POT_ROW_F_CC_BASE = 61

PC12_GREEN_BUTTON_CC_BASE = 73

PC12_ENCODER_TURN_CC = 85
PC12_ENCODER_PUSH_CC = 86
