from __future__ import absolute_import, print_function, unicode_literals


MX12_NUMBER_OF_TRACKS = 12

MX12_MIDI_CHANNEL_INDEX_SETUP_1 = 0

MX12_FADER_CC_BASE = 25
MX12_POT_ROW_A_PAN_CC_BASE = 1
MX12_POT_ROW_B_INERT_CC_BASE = 13
MX12_GRAY_BUTTON_SOLO_CC_BASE = 37
MX12_GREEN_BUTTON_MUTE_CC_BASE = 49

MX12_ENCODER_TURN_CC = 61
MX12_ENCODER_PUSH_CC = 62
